version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
  db:
    #image: mariadb
    build: database/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: noteappdb
      MYSQL_USER: noteappdb
      MYSQL_PASSWORD: password
