version: '3'
services:
  web:
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - db
  db:
    #image: mariadb
    build: database/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: noteappdb
      MYSQL_USER: noteappdb
      MYSQL_PASSWORD: password
  #web_a:
  #  build: .
  #  ports:
  #    - "8083:8083"
